branches:
  master:
    regex: ^dev(elop)?(ment)?$
    tag: ''
    increment: <<DEVELOP_INCREMENT>>
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    tracks-release-branches: true
    is-release-branch: false
    source-branches: [ 'master','release','feature','patch' ]
  feature:
    regex: ^feature[/-]
    tag: 'feature-{BranchName}'
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    tracks-release-branches: true
    is-release-branch: false
    source-branches: [ 'master','release','feature','patch' ]
  pull-request:
    regex: ^(pull|pull\-requests|pr)[/-]
    mode: ContinuousDeployment
    tag: PullRequest
    increment: None
    prevent-increment-of-merged-branch-version: false
    tag-number-pattern: '[/-](?<number>\d+)[-/]'
    track-merge-target: false
    source-branches: [ 'master', 'release', 'feature', 'patch' ]
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 30000
  patch:
    regex: ^patch[/-]
    tag: 'patch-{BranchName}'
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    tracks-release-branches: true
    is-release-branch: false
    source-branches: [ 'master','release','patch' ]
  release:
    regex: ^release[/-]
    tag: ''
    increment: <<RELEASE_INCREMENT>>
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    tracks-release-branches: false
    is-release-branch: true
    source-branches: [ 'master','patch', 'release' ]

ignore:
  sha: [ ]
merge-message-formats: { }
