branches:
  master:
    regex: ^dev(elop)?(ment)?$
    tag: ''
    increment: None
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    tracks-release-branches: true
    is-release-branch: false
    source-branches: ['master','release','feature','hotfix']
  feature:
    regex: ^features?[/-]
    tag: 'feature-{BranchName}'
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    tracks-release-branches: true
    is-release-branch: false
    source-branches: ['master','release','feature','hotfix']
  pull-request:
    regex: ^(pull|pull\-requests|pr)[/-]
    mode: ContinuousDeployment
    tag: PullRequest
    increment: None
    prevent-increment-of-merged-branch-version: false
    tag-number-pattern: '[/-](?<number>\d+)[-/]'
    track-merge-target: false
    source-branches: [ 'master', 'release', 'feature', 'hotfix' ]
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 30000
  hotfix:
    regex: ^(hot)?fix(es)?[/-]
    tag: 'hotfix-{BranchName}'
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    tracks-release-branches: true
    is-release-branch: false
    source-branches: ['master','release','hotfix']
  release:
    regex: ^releases?[/-]
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    tracks-release-branches: false
    is-release-branch: true
    source-branches: ['master','hotfix', 'release']

ignore:
  sha: []
merge-message-formats: {}
