name: CI-CD
on:
  workflow_dispatch:
  push:
    branches:
    - feature/*
    - develop
    - release/*
    - hotfix/*
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
    - develop

jobs:
  get_increment_strategies:
    runs-on: ubuntu-latest
    outputs:
      config_file: ${{ steps.get_increment_strategies.outputs.config_file }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.EDGARPAT }}
      - name: get-increment-strategies
        id: get-increment-strategies
        run: |
          parent_regex="^(hot)?fix(es)?[/-].+|^releases?[/-].+"
          actual_regex="^releases?[/-].+"
          parent_branch=$(git show-branch | grep '*' | grep -v "$(git rev-parse --abbrev-ref HEAD)" | head -n1 | sed 's/.*\[\(.*\)\].*/\1/' | sed 's/[\^~].*//')
          actual_branch=$(git symbolic-ref --short HEAD)
          if [[ $actual_branch =~ $actual_regex ]] && [[ $parent_branch =~ $parent_regex ]]
          then
            echo "config_file=VersionConfigRPatch.yaml" >> $GITHUB_OUTPUT
          else
            echo "config_file=VersionConfigRMajor.yaml" >> $GITHUB_OUTPUT
          fi

  calculate_version:
    uses: ./.github/workflows/calculate-version.yaml
    needs: [get_increment_strategies]
    secrets: inherit
    with:
      VERSION_USE_CONFIG_FILE: true
      WITH_REPO_TAGGING: true
      VERSION_CONFIG_FILE: ${{needs.calculate_version.outputs.config_file}}