name: CI-CD
on:
  workflow_dispatch:
  push:
    branches:
    - feature/*
    - develop
    - release/*
    - hotfix/*
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
    - develop

jobs:
  get_increment_strategies:
    runs-on: ubuntu-latest
    outputs:
      config_file: ${{ steps.get_increment_strategies.outputs.config_file }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.EDGARPAT }}
      - name: get_increment_strategies
        id: get_increment_strategies
        run: |
          parent_regex="^(hot)?fix(es)?[/-].+|^releases?[/-].+"
          actual_regex="^releases?[/-].+"
          parent_branch=$(git show-branch | grep '*' | grep -v "$(git rev-parse --abbrev-ref HEAD)" | head -n1 | sed 's/.*\[\(.*\)\].*/\1/' | sed 's/[\^~].*//')
          actual_branch=$(git symbolic-ref --short HEAD)
          if [[ $actual_branch =~ $actual_regex ]] && [[ $parent_branch =~ $parent_regex ]]
          then
            file_path="VersionConfigRPatch.yaml"
            
          else
            file_path="VersionConfigRMajor.yaml"
          fi
          echo "config_file=$file_path" >> $GITHUB_OUTPUT

  calculate_version:
    uses: ./.github/workflows/calculate-version.yaml
    needs: [get_increment_strategies]
    secrets: inherit
    with:
      VERSION_USE_CONFIG_FILE: true
      WITH_REPO_TAGGING: true
      VERSION_CONFIG_FILE: ${{needs.get_increment_strategies.outputs.config_file}}